### ISSUE TITLE
<additional_rule_separator> problem solved?

### ISSUE THREAD

**Issue by ypid** [simonpoole/OpeningHoursParser#1]
Hi @simonpoole 

I find your approche interesting. One question. Where you able to solve the problem where the `,` tokens has to different meanings so extensive look-ahead is needed to make a decision?

Related to: https://github.com/ypid/opening_hours.js/issues/86

**Comment by ypid** [comment]
Ping @simonpoole That is one of the burning questions :wink: Can you give some insights on that please?

**Comment by simonpoole** [comment]
IIRC I simply use an insane amount of lookahead.

**Comment by ypid** [comment]
Right. So that means you have implemented it? Is there a checklist/converge percentage of how much of the spec this project supports?

**Comment by simonpoole** [comment]
? the parser was essentially complete way back last year. forgetting
about bugs it should parse all valid oh strings and lots of invalid ones
too (case, times without leading zeros and minutes, 3 letter day
abbreviations).

I haven't checked with the current spec so there may be new things that
are not implemented (which why it would be nice to version the spec).

Am 27.06.2016 um 23:06 schrieb Robin Schneider:

**Comment by ypid** [comment]
OK, nice work! I am not aware of recent changes in the spec.

**Comment by simonpoole** [comment]
It should be noted that there are cases, simple example

10:00-12:00, 13:00-14:00

that are not unambiguous (this could be a single rule with two time spans or two separate rules).

And for example 
http://wiki.openstreetmap.org/wiki/Key:opening_hours/specification#explain:additional_rule_separator
is **clearly** a change in the specification.

**Comment by ypid** [comment]
@simonpoole Is there something which needs to be changed or clarified? I am not quite following. Your example value consists of one rule because of the restriction you mentioned.

**Comment by simonpoole** [comment]
But before you addded that restriction (that should be in the grammar proper) the result of parising it was essentially implementation dependent, afterwards not. In semantic versioning this would be a major version increase.

**Comment by ypid** [comment]
@simonpoole Thanks for the hint about semantic versioning. That is a good idea. Thanks. [Done](https://wiki.openstreetmap.org/w/index.php?title=Template:Key:opening_hours/specification_table&oldid=1319860)

> essentially implementation dependent, afterwards not.

I think that is a good thing. What is your opinion on that?
