### ISSUE TITLE
am / pm mixed with 24 h format

### ISSUE THREAD

**Issue by ges1227** [simonpoole/OpeningHoursParser#12]
Hello @simonpoole and @johnjohndoe,
I detected a weird behavior when parsing opening hours in non-strict mode such as:

|         Before         	|       After       	|
|:----------------------:	|:-----------------:	|
| Mo-Su 8:00 am -1:00 am 	| Mo-Su 08:00-25:00 	|
| Sun 9:00 am - 12:30 pm 	| Su 09:00-24:30    	|
| 12:00 pm - 3:00 pm     	| 24:00-39:00       	|
| Fri 12:00 pm - 3:30 pm 	| Fr 24:00-39:30    	|
| 7.30 am - 14.00 pm     	| 07:30-26:00       	|

Is it common, that values over 24:00 are allowed? Let me know.

**Comment by simonpoole** [comment]
Times up 48:00 are possible in the opening hours specification (extended times that extend in to the next day), naturally not all of the above were likely intended to be interpreted that way, but that is a general issue with parsing non-specification-conformant strings. Not sure if there is a reasonable heuristic that works for all of the above. The 1st example is likely correct, 2nd one see below, third should have probably been 12:00 pm - 3:00 am (isse with 12:00 pm see below), the fourth is the same as the third , the fifth might be 7:30 to 14:00.

There is however one real bug, in that times like 12:30 pm, 12:00 pm and 12:30 am need to be special cased.

**Comment by simonpoole** [comment]
https://github.com/simonpoole/OpeningHoursParser/commit/0acfaa6f5be1d90b8b7316e9e4e98cde2f9bbc9c should significantly improve the handling of > 12 hour times.

**Comment by simonpoole** [comment]
After looking through my test data and more discussions with UK colleagues I've switched the behaviour for 12 am/pm in https://github.com/simonpoole/OpeningHoursParser/commit/648099ab60432b75a14f4845a287481287815c7a

This mainly because the test data would indicate that a majority of the relevant strings use that convention. 

You test cases should now be:
