### ISSUE TITLE
List of date ranges with occurrence in month don't work

### ISSUE THREAD

**Issue by simonpoole** [simonpoole/OpeningHoursParser#13]
Jan 1-Mar Mo[1], Jun 1-Jul Tu[1] 

Will result in two rules being created instead of a list of date ranges (in other date range cases it works correctly).

**Comment by ramsestom** [comment]
This kind of rule: 
`Mar Su[-1]-Dec Su[1] -2 days;`
will fail also

**Comment by simonpoole** [comment]
@ramsestom I believe that is a separate issue as it actually works with a positive offset could simply be not adding the offset to the data structure.

**Comment by simonpoole** [comment]
@ramsestom fixed in https://github.com/simonpoole/OpeningHoursFragment/commit/16732145403ae2efc2f68a1ecfe15c43b48e54f5 it was simply a display issue in the editor, not a parser bug.
