### ISSUE TITLE
missing documentation

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/OpeningHoursParser#18]
I am looking at this library in the context of https://github.com/westnordost/StreetComplete/issues/1651 (potentially using it in StreetComplete).

Is it in active use/development? For example, is it used in a Vespucci? I see recent updates, but https://github.com/simonpoole/OpeningHoursFragment/blob/master/build.gradle seems to not be depending on it what leaves me a bit confused especially as https://github.com/simonpoole/OpeningHoursFragment/blob/master/lib/documentation/docs/help/en/Opening%20hours.md specifically refers to it. I see it in https://github.com/MarcusWolschon/osmeditor4android/blob/master/build.gradle#L460 but I worry that OpeningHoursFragment is in process of replacing it or there is some other valid reason for not using it.

Something along "is actively developed as a part of the Vespucci" or "used in the Vespucci, getting replaced by an alternative solution" would be nice. Info how it relates to OpeningHoursFragment would be great. I am guessing that OpeningHoursFragment may depend on parser interface, not specific parser - but I am not sure.

--------

What kind of dependencies it requires? Looking at https://github.com/simonpoole/OpeningHoursParser/blob/master/build.gradle#L125 it seems to be a standalone project, not pulling in avalanche of dependencies - what is a good feature and increase chance that it is going to work well on Android. It may be worth stating in README.

Is there somewhere documentation how Rule from `ArrayList<Rule> rules = parser.rules(strict);` is structured? Would it be potentially welcomed to make PR adding this info?

**Comment by simonpoole** [comment]
> ...but I worry that OpeningHoursFragment is in process of replacing it or there is some other valid reason for not using it.

OpeningHoursFragment is an Android library project and as customary has two sub-projects, the library and an example app. You are looking at the top level build file which is however not relevant for the individual dependencies of the sub projects.
 
> 
> Something along "is actively developed as a part of the Vespucci" or "used in the Vespucci, getting replaced by an alternative solution" would be nice. Info how it relates to OpeningHoursFragment would be great. I am guessing that OpeningHoursFragment may depend on parser interface, not specific parser - but I am not sure.

Given that it, while quite mature, still get fixes should make it clear that it is in active development, as I pointed out above you are simply looking in the wrong place wrt use in OpeningHoursFragment (which is simply an UI) and Vespucci (which uses it in multiple places).

 
> What kind of dependencies it requires? 
None.

> Is there somewhere documentation how Rule from `ArrayList<Rule> rules = parser.rules(strict);` is structured? Would it be potentially welcomed to make PR adding this info?

You don't really need to know the internal structure, there are getters and setters for all the internal fields, you should simply generate the javadoc locally from a clone of the repo. if javadoc is missing somewhere (in some cases it is a bit skimpy), pls feel free to make a PR with improvements.

**Comment by matkoniecz** [comment]
Thanks for a reply! Would it be welcomed to make a PR with explicit "developed as a part of the Vespucci" note in the Readme?

**Comment by simonpoole** [comment]
Well no, because there are other people using it. If anything "... originally developed for use in Vespucci" (with a link to the Vespucci repo).

**Comment by simonpoole** [comment]
Addressed in https://github.com/simonpoole/OpeningHoursParser/commit/9962f78b78928237f8e1a7b099ec2870bb3bbbe2
