### ISSUE TITLE
not found at jcenter

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/OpeningHoursParser#20]
https://github.com/simonpoole/OpeningHoursParser/#including-in-your-project was not working for me.

I succeeded to silence Gradle complaints after using rather

```
repositories {
    mavenCentral()
    maven { url 'https://dl.bintray.com/content/simonpoole/osm' }
}
```

based on https://github.com/MarcusWolschon/osmeditor4android/blob/master/build.gradle#L8

------

Note also that 

```
    maven {
        jcenter()
    }
```

for me causes complaints with Gradle from Intellijidea giving "You must specify a URL for a Maven repository."

**Comment by simonpoole** [comment]
jcenter is of a different opinion 

https://bintray.com/bintray/jcenter?filterByPkgName=OpeningHoursParser

you don't want to directly use my bintray repo because you will not be able to publish on F-Droid that way.

In any case the correct syntax  is:

```
repositories {
....
   jcenter()
....
}
```
