### ISSUE TITLE
Specify how to build jar file

### ISSUE THREAD

**Issue by eddywatta** [simonpoole/OpeningHoursParser#27]
Add some instructions to the README.md that explains how to build the project jar file. For example I run the command: "gradlew.bat jar" that created the file "/build/libs/OpeningHoursParser-0.18.0.jar". It looks like an obviousness but I've spent some time to figure it out.

Thank you

**Comment by simonpoole** [comment]
Addressed in https://github.com/simonpoole/OpeningHoursParser/commit/d5a6b33ad8f66f02220386003b8c89457f7a1193
