### ISSUE TITLE
Provide translations for error messages

### ISSUE THREAD

**Issue by simonpoole** [simonpoole/OpeningHoursParser#29]
See also https://github.com/simonpoole/OpeningHoursParser/pull/28

**Comment by simon04** [comment]
@simonpoole, are you configuring and setting up Transifex for i18n?

**Comment by simonpoole** [comment]
Yes that is done see https://github.com/simonpoole/OpeningHoursParser/commit/e40e524f39027f315842444b422d92da5efeda23 .  I'll make an announcement there sometime today too.

Feature added in https://github.com/simonpoole/OpeningHoursParser/commit/e40e524f39027f315842444b422d92da5efeda23

**Comment by simonpoole** [comment]
Seems as if I need to fix up the base line data for the test against OSM data, but that is only a superficial issue.
