### ISSUE TITLE
Fine grained version of strict mode

### ISSUE THREAD

**Issue by simonpoole** [simonpoole/OpeningHoursParser#40]
Currently the parser behaves black and white, either you are running in strict node, or you are not. In some cases (the thoughts on this prompted by https://github.com/simonpoole/OpeningHoursParser/issues/39) you might want finer grade control over which practices cause an error and which not.

It would be rather simple to provide configuration for the existing 12 "errors" we allow and adding such a facility would allow us to make the 4 relaxations we have in strict mode optional too without being unpracticality strict.

Thoughts anybody?

**Comment by simonpoole** [comment]
Emitting the warnings would definitely be possible, and further down the road I intend (well some of it has already been done) to do some work on trying to restart after a parse error so that we can report multiple errors in one.

As to the 2nd point that probably belongs in an evaluator and not in the parser (there is obviously some grey area in between), some work has already been done, I've just not got around to having a look at it yet.

**Comment by westnordost** [comment]
I agree on point 2, it could be a separate library that depends on this one. Though I think many users of this library would also like to get validation information that (and other) would be cobbled together by that evaluator

**Comment by simonpoole** [comment]
https://github.com/simonpoole/OpeningHoursParser/commit/d829f97db54c33e6306bc2283f8cdd567b5b8c59 adds a flag to control the behaviour for extended hours which is a slightly controversial topic. During this years GSOC an evaluator was developed that hasn't been integrated anywhere yet, but that is planned for later this year.

Version 0.23 added some support for restarting the parser so multiple parse errors can now be returned (https://github.com/simonpoole/OpeningHoursParser/releases/tag/0.23.0)
