### ISSUE TITLE
False warning with SH, PH on weekdays

### ISSUE THREAD

**Issue by Newbie07** [simonpoole/OpeningHoursParser#41]
From https://josm.openstreetmap.de/ticket/18857:

> ==== What steps will reproduce the problem?
> 1. Have `opening_hours=10:00-17:00; Jan-Mai,Nov-Dec Mo off; PH,SH Mo 09:00-17:00` (every Mo if SH or PH open)
> 1. Run validator
> 
> ==== What is the expected result?
> No warning
> 
> ==== What happens instead?
> I get: `Encountered:  <HYPHEN> "- " at line 1, column 14Was expecting: <EOF> (1)`
> 
> ==== Please provide any additional information below. Attach a screenshot if possible.
> Additional, the warning is not human readable and autofix misses.

**Comment by Newbie07** [comment]
I am wrong. Thought the warning is about PH and SH but it is about "Mai" German for "May" and correct

**Comment by simonpoole** [comment]
Currently the automatically (that is by the parser generator) created message are sometimes a bit difficult to understand, due to the fact that the way things are setup it will generate a parser error instead of  complaining about an unknown token.
