### ISSUE TITLE
Only first error mentioned

### ISSUE THREAD

**Issue by Newbie07** [simonpoole/OpeningHoursParser#42]
If there are more than one issue only the first one is reported e.g.:
`08:00-17:00; Jan-Mai,Nov-Dez Mo off; PH,SH 10:00-17:00; Dez 1 off`

should flag `Mai` and both occurrences of `Dez`, possibly all in one message.

**Comment by simonpoole** [comment]
Support added in https://github.com/simonpoole/OpeningHoursParser/commit/675acfeea984a5a5e0ea4350bc97659522a22a3f
