### ISSUE TITLE
Handling "off" days

### ISSUE THREAD

**Issue by eddywatta** [simonpoole/OpeningHoursParser#43]
I'm wondering how the parser handle the word "off" in a rule, i.e. the rule "We off". It seems that the word is ignored in fact I have the same results with the rule "We".
Am I missing something? How can I know if the rule means open or close ("off")? 

Thanks for all

**Comment by simonpoole** [comment]
I'm not quiet sure what you are looking for, the parser adds a Modifier object to the data structure it generates with a value of "OFF".

**Comment by eddywatta** [comment]
That is exacty what I'm looking for!

Thank you very much
