### ISSUE TITLE
Add <url> and <license> in generated pom

### ISSUE THREAD

**Issue by simon04** [simonpoole/OpeningHoursParser#46]
Can you add `<url>` and `<license>` to https://dl.bintray.com/simonpoole/osm/ch/poole/OpeningHoursParser/0.21.3/OpeningHoursParser-0.21.3.pom

Gradle docs: https://docs.gradle.org/current/dsl/org.gradle.api.publish.maven.MavenPublication.html#org.gradle.api.publish.maven.MavenPublication

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>ch.poole</groupId>
  <artifactId>OpeningHoursParser</artifactId>
  <version>0.21.3</version>
</project>
```

Example having the elements: https://repo1.maven.org/maven2/org/tukaani/xz/1.8/xz-1.8.pom

**Comment by simonpoole** [comment]
Added in https://github.com/simonpoole/OpeningHoursParser/commit/eb0b742e4f6d84f93297e6919b2c837b054cdc7c

**Comment by simon04** [comment]
Thank you!
