### ISSUE TITLE
non-strict mode: Allow no space after months if there is a colon

### ISSUE THREAD

**Issue by westnordost** [simonpoole/OpeningHoursParser#50]
I noticed that these opening hours `Oct-Mar:07:00-20:00; Apr:07:00-22:00; May-Sep:07:00-23:00` ([node#3736714410](https://www.openstreetmap.org/node/3736714410)) are not parseable by the parser.

I reckon that this is because there is no space after the colon of the month(s range(s)). Non-strict mode could allow to have no spaces after the months if there is no colon.

**P.S:** StreetComplete is now using this parser, works like a charm, thank you! [I've written a (StreetComplete centric) test](https://github.com/westnordost/StreetComplete/blob/be4277c004e3f4cc4a1c8eae1934bbd192a0f812/app/src/test/java/de/westnordost/streetcomplete/OpeningHoursParsingTest.kt) to see how much percent of opening hours strings are parseable, and how much of these are supported by StreetComplete. [If you are interested, these are the results](https://github.com/westnordost/StreetComplete/pull/2045#issuecomment-678838772). **97.7% of all opening hours strings worldwide can be parsed by OpeningHoursParser (non-strict mode)**

**Comment by simonpoole** [comment]
This is actually a bit tricky, the problem is that the choice is ambiguous (the parser doesn't actually require the space but it forces a different choice to be made). Probably needs some liberal use of semantic lookahead.

**Comment by simonpoole** [comment]
@westnordost see https://github.com/simonpoole/OpeningHoursParser/pull/54

**Comment by westnordost** [comment]
Nice!

Am 5. Januar 2021 12:00:11 MEZ schrieb Simon Poole <notifications@github.com>:
>@westnordost see
>https://github.com/simonpoole/OpeningHoursParser/pull/54
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/simonpoole/OpeningHoursParser/issues/50#issuecomment-754565312

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by simonpoole** [comment]
> I reckon that this is because there is no space after the colon of the month(s range(s)). Non-strict mode could allow to have no spaces after the months if there is no colon.

The spec doesn't seem to require a space, not that it is anything to go by in that respect it is more or less random that is why I've in general just ignored them in the parser, however I could now enforce them if necessary with the changes in https://github.com/simonpoole/OpeningHoursParser/commit/083f7c8d35dec9c1fed63d3aa5e1b23c53c07398

**Comment by simonpoole** [comment]
Changed in https://github.com/simonpoole/OpeningHoursParser/pull/54
