### ISSUE TITLE
Equivalent to the opening_hours.js Simple API

### ISSUE THREAD

**Issue by ukasiu** [simonpoole/OpeningHoursParser#51]
Hi all,

is there an equivalent in Java to opening_hours.js Simple API (https://github.com/opening-hours/opening_hours.js#simple-api)? I mean functions to tell whether _facility_ is open, when will be closed at the moment, etc.

**Comment by simonpoole** [comment]
There is work in progress by @lenonardehrenfried https://github.com/leonardehrenfried/opening-hours-evaluator that will do that.
