### ISSUE TITLE
Standalone holiday values get duplicated in weekdays

### ISSUE THREAD

**Issue by simonpoole** [simonpoole/OpeningHoursParser#52]
Reported in https://github.com/MarcusWolschon/osmeditor4android/issues/1245

Fixed in https://github.com/simonpoole/OpeningHoursParser/commit/eb9ce14c885e0a9f57f555db370fde554765c5d0

@simon04  @westnordost unluckily I won't be able to publish the corrected version to bintray before Sunday evening, sorry that this slipped through testing.

**Comment by westnordost** [comment]
Thanks for the notification, Simon! :-) I'll issue an update as soon as the fix is available.

**Comment by simonpoole** [comment]
Available on 0.22.1 is available on bintray now.
