### ISSUE TITLE
Clarify meaning of PH/SH

### ISSUE THREAD

**Issue by simonpoole** [simonpoole/OpeningHoursParser#6]
The spec now seems to be using 

```
<singular_day_holiday>
```

and 

```
<plural_day_holiday>
```

in place of the original school and public holiday.

And yes the new interpretation should likely be: single_day_holiday and multiple_day_holiday I suspect from a language pov, however as outlined below this would reverse the meaning of the values, rendering 10s of 100s of OH values wrong.

**Comment by ypid** [comment]
Sounds good. `multiple_day_holiday` is the better name for it. Please go ahead: https://wiki.openstreetmap.org/wiki/Template:Key:opening_hours/specification_table

**Comment by simonpoole** [comment]
@ypid 
The problem is that the change reverses the semantics of SH/PH.

School holidays tend to be multiple days, mostly weeks.

Public holidays single or a low number of days.

So I believe the spec change should be reverted.

**Comment by ypid** [comment]
How would you handle the [`<singular_day_holiday> [ <day_offset> ]`](https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification#holiday) part then?

**Comment by simonpoole** [comment]
My understanding of the semantics was that this  defines a day prior to or after the holiday in question, typical use would be special closing times on the day before a public holiday. But my understanding is that it is a seperate day than the span defined by the holiday itself.

Note that the example given on https://github.com/opening-hours/opening_hours.js#holidays
does not match the spec which allows:

    <holiday-range> <weekday- range>
and

    <holiday-range> , <weekday-range>

but not 

    <weekday- range> , <holiday-range>

**Comment by ypid** [comment]
> <weekday- range> , <holiday-range>

You are right. Thanks for the hint. I guess we can extend the spec. Any reason against this?

> But my understanding is that it is a seperate day than the span defined by the holiday itself.

I am not quite following. You mean something like `SH -1 day`? I don’t really think that is used and thus it is not allowed in the spec.

**Comment by simonpoole** [comment]
> 
> 
>     <weekday- range> , <holiday-range>
> 
> You are right. Thanks for the hint. I guess we can extend the spec. Any reason against this?

Lots of reasons, but mainly that the spec doesn't get better and easier to handle by adding yet another variant, the opposite should happen: <holiday-range>, <weekday- range> should be deprecated and only  <holiday-range> <weekday- range> should remain.
