### ISSUE TITLE
Hours and minutes for interval

### ISSUE THREAD

**Issue by goodudetheboy** [simonpoole/OpeningHoursParser#62]
For the pattern points in time in timespan, or setting interval, the `<hour_minutes>` is not supported by the parser (see [specification](https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification#explain:timespan:points-in-time:shortcut)). For example, parsing `13:00-19:00/90` results in 
```
TimeSpan:13:00-19:00/01:30
```
but parsing `13:00-19:00/1:30` or `13:00-19:00/01:30` results in
```
ch.poole.openinghoursparser.OpeningHoursParseException: Encountered:  ":" ": " at line 1, column 13
``` 
throwing an error.

**Comment by simonpoole** [comment]
Thanks for the report.

Fixed in https://github.com/simonpoole/OpeningHoursParser/commit/78203e45245fa7c75179fb52f69d45a77822ce9e
