### ISSUE TITLE
Open end for year not supported

### ISSUE THREAD

**Issue by goodudetheboy** [simonpoole/OpeningHoursParser#65]
It seems that parsing for open end for year is not currently supported. When I try parsing an OH string like "2021+", the parser throws this error:
```
ch.poole.openinghoursparser.OpeningHoursParseException: Encountered:  "+" "+ " at line 1, column 1
Was expecting: <EOF>
        at ch.poole.openinghoursparser.OpeningHoursParser.rules(OpeningHoursParser.java:47)

        at ch.poole.openinghoursparser.IndividualTest.main(IndividualTest.java:25)
```

**Comment by simonpoole** [comment]
Added in https://github.com/simonpoole/OpeningHoursParser/commit/7cf8a65eb6a3ad1132a7f0a716ac424f924d1b16

There are currently only 4 correct usages of this in all OSM data, and nothing in the test data set so not a big surprise that I missed it.
