### ISSUE TITLE
Fails with JavaCC 6.1.3

### ISSUE THREAD

**Issue by sebastic** [simonpoole/OpeningHoursParser#72]
As reported in [Debian Bug #1011131](https://bugs.debian.org/1011131):
> josm fails to build with JavaCC 6:
> ```
>     [javac] /<<PKGBUILDDIR>>/src/ch/poole/openinghoursparser/OpeningHoursParserTokenManager.java:1182: error: incompatible types: possible lossy conversion from int to char
>     [javac]      throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
>     [javac]                                                                                           ^
> ```
> This can be fixed by building with the javacc5 package instead of javacc

ant task used to generate the code:
```xml
   <target name="javacc-openinghoursparser" depends="init" unless="javacc.notRequired">
       <mkdir dir="${src.dir}/ch/poole/openinghoursparser/parsergen"/>
       <exec append="false" executable="javacc" failifexecutionfails="true">
           <arg value="-DEBUG_PARSER=false"/>
           <arg value="-DEBUG_TOKEN_MANAGER=false"/>
           <arg value="-JDK_VERSION=1.${java.lang.version}"/>
           <arg value="-GRAMMAR_ENCODING=UTF-8"/>
           <arg value="-UNICODE_INPUT=true"/>
           <arg value="-OUTPUT_DIRECTORY=${src.dir}/ch/poole/openinghoursparser"/>
           <arg value="${src.dir}/ch/poole/openinghoursparser/OpeningHoursParser.jj"/>
       </exec>
   </target>
```

**Comment by simonpoole** [comment]
Not really a bug as there was/is no expectation one way or the other that it would build with JavaCC 6. I'll have a look at it ASAP.

**Comment by simonpoole** [comment]
@sebastic which javacc version were you actually using? I can't find a published 6.0.0 artifact, and, fun, with 6.1.2 things compile (and pass tests) just fine.

**Comment by sebastic** [comment]
6.1.3: https://tracker.debian.org/pkg/javacc

The javacc Debian package used the [release_6_1_3](https://github.com/javacc/javacc/releases/tag/release_6_1_3) tag to get the sources.

**Comment by simonpoole** [comment]
Sigh, see https://github.com/javacc/javacc/releases/tag/release_6_1_3 never actually published and not backwards compatible with prior 6.1 versions it seems. 

Don't think this is cleanly fixable before Debian switches to an actually released version of JavaCC.

**Comment by sebastic** [comment]
The javacc package in Debian has been updated to 7.0.11 which has the same issue:
```
    [javac] /build/josm-0.0.svn18427+dfsg/src/ch/poole/openinghoursparser/OpeningHoursParserTokenManager.java:1183: error: incompatible types: possible lossy conversion from int to char
    [javac]      throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
    [javac]                                                                                           ^
```
