### ISSUE TITLE
Time ranges until and over midnight are rejected

### ISSUE THREAD

**Issue by MichaelMarte-TomTom** [simonpoole/OpeningHoursParser#73]
The parser rejects time ranges until and over midnight, e.g. 08:30-24:00 and 12:00-04:00, also in non-strict mode.

https://openingh.openstreetmap.de/evaluation_tool/ parses both examples.

The examples were taken from:

- https://www.openstreetmap.org/way/6613090
- https://www.openstreetmap.org/way/38910458

**Comment by simonpoole** [comment]
That was "fixed" over a year ago https://github.com/simonpoole/OpeningHoursParser/commit/d829f97db54c33e6306bc2283f8cdd567b5b8c59

**Comment by MichaelMarte-TomTom** [comment]
Thanks, I was not aware of the `strictTime` parameter.

**Comment by simonpoole** [comment]
Note that it has never rejected such time ranges in non-strict mode, what did change ~2years ago is that we removed the conversion to extended time format if the time range was shorter than 24h (aka we started retaining the original times). If you are having issues in non-strict mode, pls reopen the issue.
