### ISSUE TITLE
Canonical form: Jumbled order of nth weekdays

### ISSUE THREAD

**Issue by westnordost** [simonpoole/OpeningHoursParser#79]
This parser outputs a canonical form of the parsed opening hours string for better readability. However, there seems to be a bug for nth weekdays.

E.g. "all Sundays except the 2nd Sunday of each month": `Su[1,3,4,5]` is changed to `Su[1,5,4,3]`.

This does not increase readability, actually, why change the order at all?

**Comment by simonpoole** [comment]
Without actually checking, I'm fairly sure that us an artifact of how the numbers are collected during parsing and it is just missing a Collections.reverse at some point.
