### ISSUE TITLE
Add missing release tags

### ISSUE THREAD

**Issue by johnjohndoe** [simonpoole/OpeningHoursParser#8]
I noticed that you increased the version of the library a couple of times. Here on GitHub I cannot find a release tag for these versions (`0.1.1`, `0.1.2`, ...). Please add the missing tags and push them:

```
git checkout a2909
git tag -a "0.1.1" -m "Brief summary of the changes."
git push --tags origin
```

**Comment by ypid** [comment]
@johnjohndoe `git tag` also accepts the commit reference :wink:
Also note that at least git tags SHOULD be cryptographically signed using OpenPGP. This could look like this:

```shell
git tag -a "0.1.1" -s -m "Brief summary of the changes." a2909
git push --tags origin
```

**Comment by johnjohndoe** [comment]
@ypid Nice, thanks for the Git tip!

**Comment by simonpoole** [comment]
0.1.2 tagged

**Comment by johnjohndoe** [comment]
:+1: It would be great if you could add the other versions as well so it is easier to find the versions if needed. 

---

Somewhat related: For your interest - I just found this very helpful website: http://keepachangelog.com
