### ISSUE TITLE
End time earlier than start time considered not valid

### ISSUE THREAD

**Issue by westnordost** [simonpoole/OpeningHoursParser#82]
A time span like `22:00-05:00` is not considered valid in strict mode, even though

- it is [described as valid in the specification](https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification#explain:extended_hour_minutes) and 

- this parser itself pretty-prints `22:00-29:00` as `22:00-05:00`. (So, it currently creates strings that itself considers invalid)

**Comment by simonpoole** [comment]
As I previously pointed out https://github.com/simonpoole/OpeningHoursParser/issues/80#issuecomment-1881145178, mentioned in the README and in the JavaDoc https://github.com/simonpoole/OpeningHoursParser/blob/master/src/main/java/ch/poole/openinghoursparser/OpeningHoursParser.jj#L79  the behaviour wrt times is configurable.
