### ISSUE TITLE
Weekdays with mixed-in holidays not sorted correctly

### ISSUE THREAD

**Issue by westnordost** [simonpoole/OpeningHoursParser#87]
The readme states:

> In non-strict mode the following further differences are allowed:
> [...]
> - holidays in weekday range

and this also works. However, the expectation is that holidays mixed into weekday ranges are sorted correctly either to the front or back (both is allowed) when pretty-printing it so that the outputted string is a valid opening hours string. This does not work for e.g.

`PH,Su,SH,Tu-Fr 18:00-20:00`

It is simply changed to `PH,Su, SH,Tu-Fr 18:00-20:00`.

**Comment by simonpoole** [comment]
I quote from the code :-)

 // holiday handling is painful
