### ISSUE TITLE
Top level comment parsing

### ISSUE THREAD

**Issue by simonpoole** [simonpoole/OpeningHoursParser#9]
The syntax is not completely clear (does it need double quotes or not) and the parsing seems to be slightly broken.

**Comment by simonpoole** [comment]
Fixed as far as possible in https://github.com/simonpoole/OpeningHoursParser/commit/2411f7df630d682abb970e1a0e38f12c7fd02806

**Comment by ypid** [comment]
Is the [specification on comments](https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification#comment) not clear enough? How can it be improved?

**Comment by simonpoole** [comment]
Yes, it now refers to normal comments in double quotes a la  "comment text" :
But there are examples without quotes and iirc historically it wasn't a quoted string in the spec either.

**Comment by ypid** [comment]
As long as I have been involved it was using double quotes. But that feature is certainly one of the really used once.
