### ISSUE TITLE
Is there functionality for going from a correctly-formatted opening_hours string to an "absolute" version?

### ISSUE THREAD

**Issue by iboates** [simonpoole/OpeningHoursParser#90]
I am poking around in the library right now and I thought that I would be able to go in the opposite direction as usual, that is to say to take the string for `opening_hours` as it appears on OSM and convert it into a list of more "absolute" values, like individual intervals for each day of the week.

Something like:

```
Mo-Fr 09:00-12:00, 14:00-18:30; Sa 09:00-12:00, 14:00-17:00
```

would be converted into

```
[
  {"monday": [
    {"open": "09:00", "close": "12:00"},
    {"open": "14:00", "close": "18:30"}
  },
  "tuesday": [
    {"open": "09:00", "close": "12:00"},
    {"open": "14:00", "close": "18:30"}
  },
  ...
]
```

It doesn't have to explicitly be a JSON, it's just meant to illustrate the idea of going from this single string to a series of absolute time intervals. I realize there would also be considerations regarding public holidays and other exceptions.

Is this handled in this library? Or is it not meant for this use case?

**Comment by simonpoole** [comment]
There is a 'companion' eval library that is not well used because of issues with the timezone library it uses, but in a desktop/server environment it works https://github.com/goodudetheboy/OpeningHoursEvaluator
